In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from matplotlib.image import imread

In [76]:
df=pd.read_csv('C:/Users/User/Downloads/02450Group7-main/02450Group7-main/Data/day_n.csv')

In [77]:
df.head()

instant    dteday  season  year  month holiday weekday workingday  \
0        1  1/1/2011       1     0      1      No     Sat         No   
1        2  1/2/2011       1     0      1      No     Sun         No   
2        3  1/3/2011       1     0      1      No     Mon        Yes   
3        4  1/4/2011       1     0      1      No     Tue        Yes   
4        5  1/5/2011       1     0      1      No     Wed        Yes   

  weathersit      temp     atemp      hum  windspeed  casual  registered  \
0       Mist  8.175849  7.999250  80.5833  10.749882     331         654   
1       Mist  9.083466  7.346774  69.6087  16.652113     131         670   
2      Clear  1.229108 -3.499270  43.7273  16.636703     120        1229   
3      Clear  1.400000 -1.999948  59.0435  10.739832     108        1454   
4      Clear  2.666979 -0.868180  43.6957  12.522300      82        1518   

   count  
0    985  
1    801  
2   1349  
3   1562  
4   1600

In [78]:
df=df.drop(columns=['instant','dteday','casual','registered'])

In [79]:
df

season  year  month holiday weekday workingday weathersit      temp  \
0         1     0      1      No     Sat         No       Mist  8.175849   
1         1     0      1      No     Sun         No       Mist  9.083466   
2         1     0      1      No     Mon        Yes      Clear  1.229108   
3         1     0      1      No     Tue        Yes      Clear  1.400000   
4         1     0      1      No     Wed        Yes      Clear  2.666979   
..      ...   ...    ...     ...     ...        ...        ...       ...   
726       1     1     12      No     Thu        Yes       Mist  3.945849   
727       1     1     12      No     Fri        Yes       Mist  3.906651   
728       1     1     12      No     Sat         No       Mist  3.906651   
729       1     1     12      No     Sun         No      Clear  4.024151   
730       1     1     12      No     Mon        Yes       Mist  2.144151   

        atemp      hum  windspeed  count  
0    7.999250  80.5833  10.749882    985  
1    7.346774  69.6087  16.652113    801  
2   -3.499270  43.7273  16.636703   1349  
3   -1.999948  59.0435  10.739832   1562  
4   -0.868180  43.6957  12.522300   1600  
..        ...      ...        ...    ...  
726 -1.041628  65.2917  23.458911   2114  
727  0.833036  59.0000  10.416557   3095  
728 -0.001600  75.2917   8.333661   1341  
729 -0.707800  48.3333  23.500518   1796  
730 -1.249858  57.7500  10.374682   2729  

[731 rows x 12 columns]

In [80]:
df['holiday']=df['holiday'].astype('category')
df['holiday']=df['holiday'].cat.codes
df['weekday']=df['weekday'].astype('category')
df['weekday']=df['weekday'].cat.codes
df['workingday']=df['workingday'].astype('category')
df['workingday']=df['workingday'].cat.codes
df['weathersit']=df['weathersit'].astype('category')
df['weathersit']=df['weathersit'].cat.codes
df

season  year  month  holiday  weekday  workingday  weathersit      temp  \
0         1     0      1        0        2           0           2  8.175849   
1         1     0      1        0        3           0           2  9.083466   
2         1     0      1        0        1           1           0  1.229108   
3         1     0      1        0        5           1           0  1.400000   
4         1     0      1        0        6           1           0  2.666979   
..      ...   ...    ...      ...      ...         ...         ...       ...   
726       1     1     12        0        4           1           2  3.945849   
727       1     1     12        0        0           1           2  3.906651   
728       1     1     12        0        2           0           2  3.906651   
729       1     1     12        0        3           0           0  4.024151   
730       1     1     12        0        1           1           2  2.144151   

        atemp      hum  windspeed  count  
0    7.999250  80.5833  10.749882    985  
1    7.346774  69.6087  16.652113    801  
2   -3.499270  43.7273  16.636703   1349  
3   -1.999948  59.0435  10.739832   1562  
4   -0.868180  43.6957  12.522300   1600  
..        ...      ...        ...    ...  
726 -1.041628  65.2917  23.458911   2114  
727  0.833036  59.0000  10.416557   3095  
728 -0.001600  75.2917   8.333661   1341  
729 -0.707800  48.3333  23.500518   1796  
730 -1.249858  57.7500  10.374682   2729  

[731 rows x 12 columns]

In [11]:
df.isnull().sum()

season        0
year          0
month         0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
count         0
dtype: int64

In [13]:
df.shape

(731, 12)

In [14]:
X=df.drop(columns='workingday')
X

season  year  month  holiday  weekday  weathersit      temp     atemp  \
0         1     0      1        2        2           2  8.175849  7.999250   
1         1     0      1        3        3           2  9.083466  7.346774   
2         1     0      1        1        1           0  1.229108 -3.499270   
3         1     0      1        5        5           0  1.400000 -1.999948   
4         1     0      1        6        6           0  2.666979 -0.868180   
..      ...   ...    ...      ...      ...         ...       ...       ...   
726       1     1     12        4        4           2  3.945849 -1.041628   
727       1     1     12        0        0           2  3.906651  0.833036   
728       1     1     12        2        2           2  3.906651 -0.001600   
729       1     1     12        3        3           0  4.024151 -0.707800   
730       1     1     12        1        1           2  2.144151 -1.249858   

         hum  windspeed  count  
0    80.5833  10.749882    985  
1    69.6087  16.652113    801  
2    43.7273  16.636703   1349  
3    59.0435  10.739832   1562  
4    43.6957  12.522300   1600  
..       ...        ...    ...  
726  65.2917  23.458911   2114  
727  59.0000  10.416557   3095  
728  75.2917   8.333661   1341  
729  48.3333  23.500518   1796  
730  57.7500  10.374682   2729  

[731 rows x 11 columns]

In [15]:
y=df['workingday']
y

0      0
1      0
2      1
3      1
4      1
      ..
726    1
727    1
728    0
729    0
730    1
Name: workingday, Length: 731, dtype: int8

In [16]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [21]:
X_train

season  year  month  holiday  weekday  weathersit       temp      atemp  \
537       3     1      6        4        4           0  29.874151  33.667772   
400       1     1      2        3        3           2   4.494151   1.458386   
429       1     1      3        1        1           0   3.436651  -0.082714   
13        1     0      1        0        0           0  -0.439110  -3.564742   
626       3     1      9        5        5           2  21.296651  21.294422   
..      ...   ...    ...      ...      ...         ...        ...        ...   
419       1     1      2        0        0           2  11.152500  11.124086   
120       2     0      5        3        3           2  13.228349  13.581464   
368       1     1      1        6        6           2  -2.947500  -8.123758   
48        1     0      2        0        0           0  16.518349  17.790878   
207       3     0      7        6        6           0  28.425000  29.584022   

         hum  windspeed  count  
537  56.7917   7.958729   5905  
400  68.7917  11.791732   2947  
429  50.6250  15.333486   3333  
13   53.7826   8.478716   1421  
626  87.2500  23.958329   4073  
..       ...        ...    ...  
419  73.7500  15.916989   3487  
120  76.2083   7.125718   3351  
368  41.4583  12.374900   2368  
48   51.6667  17.749975   2927  
207  40.2917  12.292021   4656  

[584 rows x 11 columns]

In [22]:
X_test

season  year  month  holiday  weekday  weathersit       temp      atemp  \
353       4     0     12        5        5           2  10.134151  10.165964   
712       4     1     12        4        4           0   5.904151   3.416408   
119       2     0      4        2        2           0  14.207500  14.625386   
22        1     0      1        3        3           0  -3.463480  -9.476619   
655       4     1     10        6        6           0  13.424151  13.707128   
..      ...   ...    ...      ...      ...         ...        ...        ...   
146       2     0      5        0        0           0  24.038349  26.042528   
397       1     1      2        4        4           2  10.760849  10.332086   
629       3     1      9        0        0           0  20.160849  21.750086   
555       3     1      7        1        1           2  25.409151  27.167564   
55        1     0      2        0        0           2   9.124356   7.130426   

         hum  windspeed  count  
353  59.5417   4.125244   3750  
712  48.5833  11.666643   5532  
119  50.3333  15.750025   5312  
22   43.6522  16.522200    986  
655  69.2917   6.791857   7461  
..       ...        ...    ...  
146  65.3750  16.125493   4679  
397  67.2917  12.541529   3761  
629  66.8750  10.333343   8167  
555  68.3333  12.125325   6569  
55   71.2174  23.218113   1461  

[147 rows x 11 columns]

In [23]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler=StandardScaler()

In [26]:
X_train_scaled=scaler.fit_transform(X_train)

In [27]:
X_test_scaled=scaler.transform(X_test)

In [28]:
X_train_scaled

array([[ 0.44141588,  0.98977827, -0.15752919, ..., -0.45429463,
        -0.91548247,  0.73905497],
       [-1.34257631,  0.98977827, -1.30034968, ...,  0.3987652 ,
        -0.1777864 , -0.76813127],
       [-1.34257631,  0.98977827, -1.01464456, ..., -0.89267496,
         0.50385618, -0.57145315],
       ...,
       [-1.34257631,  0.98977827, -1.58605481, ..., -1.54432026,
        -0.06555044, -1.06314846],
       [-1.34257631, -1.0103273 , -1.30034968, ..., -0.81862226,
         0.96893133, -0.77832185],
       [ 0.44141588, -1.0103273 ,  0.12817593, ..., -1.62725189,
        -0.08150125,  0.10265348]])

In [29]:
X_test_scaled

array([[ 1.33341197, -1.0103273 ,  1.55670154, ..., -0.25880175,
        -1.65327139, -0.35897963],
       [ 1.33341197,  0.98977827,  1.55670154, ..., -1.03781598,
        -0.2018609 ,  0.54900072],
       [-0.45058022, -1.0103273 , -0.72893944, ..., -0.91341143,
         0.58402288,  0.43690438],
       ...,
       [ 0.44141588,  0.98977827,  0.69958617, ...,  0.26251022,
        -0.45846654,  1.89160916],
       [ 0.44141588,  0.98977827,  0.12817593, ...,  0.36617832,
        -0.11358341,  1.07738211],
       [-1.34257631, -1.0103273 , -1.30034968, ...,  0.57120414,
         2.02132392, -1.52529109]])

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
log_reg=LogisticRegression(random_state=0).fit(X_train_scaled,y_train)

In [32]:
log_reg.predict(X_train_scaled)

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [33]:
log_reg.score(X_train_scaled,y_train)

0.6421232876712328

In [34]:
log_reg.score(X_test_scaled,y_test)

0.6666666666666666

In [58]:
log_reg1=LogisticRegression(random_state=0,
                           C=0.01,
                            fit_intercept=True,
                           ).fit(X_train_scaled,y_train)

#c=regularization parameter

In [59]:
log_reg1.score(X_train_scaled,y_train)

0.6763698630136986

In [60]:
log_reg.score(X_test_scaled,y_test)

0.6666666666666666