In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
# Read file and store as pandas dataframe
filename = '../Data/day.csv'
df = pd.read_csv(filename)

for attribute in ['instant','dteday','yr','mnth','holiday','weekday','casual','registered']:
    df = df.drop(attribute, axis=1)

N, M = df.shape
attributeNames = list(df.columns)

# Get column indexes
season_col = df.columns.get_loc("season")
temp_col = df.columns.get_loc("temp")
atemp_col = df.columns.get_loc("atemp")
hum_col = df.columns.get_loc("hum")
wspd_col = df.columns.get_loc("windspeed")
cnt_col = df.columns.get_loc("cnt")

# Undo the original max-min normalization
X = df.values
for row in range(0, N):
    X[row, temp_col] = X[row, temp_col]*(39-(-8)) + (-8)
    X[row, atemp_col] = X[row, atemp_col]*(50-(-16)) + (-16)
    X[row, hum_col] = X[row, hum_col]*100
    X[row, wspd_col] = X[row, wspd_col]*67

# Standarize ratio data attributes
for col in range(temp_col, cnt_col+1):
    # subtract mean, column by column
    mn = X[:, col].mean(0)
    std = np.std(X[:, col])
    X[:, col] = (X[:, col] - np.ones(N)*mn)/std


In [3]:
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = np.array(data)
print(values)

# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
# print(integer_encoded)

# binary encode
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [4]:
data = [1,1,1,3,3,2,2,4,4]
values = np.array(data)

# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
# print(integer_encoded)

# # binary encode
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [5]:
print(integer_encoded.shape)
# print(seasons.shape)
print(X[:,season_col].shape)

(9, 1)
(731,)


In [6]:
data = X[:,season_col]
values = np.array(data)

# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
# print(integer_encoded)

# # binary encode
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [7]:
print(onehot_encoded[154])
print(season_col)

[0. 1. 0. 0.]
0


In [8]:
label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder(sparse_output=False)

for col in [0,3,4,5,6]:
    data = X[:,col]
    values = np.array(data)

    # integer encode
    integer_encoded = label_encoder.fit_transform(values)

    # binary encode
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
#     for i in range(N):
#         X[i,col] = onehot_encoded[i]   # gives ValueError
    print(onehot_encoded)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
X.shape

(731, 8)

In [10]:
# # Converting type of columns to category
# df['season']=df['season'].astype('category')
# df['weathersit']=df['weathersit'].astype('category')
 
# # Assigning numerical values and storing it in another columns
# df['season_new']=df['season'].cat.codes
# df['weathersit_new']=df['weathersit'].cat.codes
 
# #Passing encoded columns
# '''
# NOTE: we have converted the enc.fit_transform() method to array because the fit_transform method
# of OneHotEncoder returns SpiPy sparse matrix this enables us to save space when we
# have huge  number of categorical variables
# '''
# enc_data=pd.DataFrame(onehot_encoder.fit_transform(df[['season_new','weathersit_new']]).toarray())
 
# #Merge with main
# New_df=df.join(enc_data)
 
# print(New_df)

# # one_hot_encoded_data = pd.get_dummies(df, columns = ['season','weathersit'])
# # print(one_hot_encoded_data)

In [11]:
# one_hot_encoded_df = pd.get_dummies(df, columns = ['season','weathersit'])
one_hot_encoded_df = pd.get_dummies(df, columns = ['season','weathersit','workingday'])
one_hot_encoded_df.shape

(731, 14)

In [12]:
one_hot_encoded_df

temp     atemp       hum  windspeed   cnt  season_1  season_2  \
0    0.344167  0.363625  0.805833   0.160446   985         1         0   
1    0.363478  0.353739  0.696087   0.248539   801         1         0   
2    0.196364  0.189405  0.437273   0.248309  1349         1         0   
3    0.200000  0.212122  0.590435   0.160296  1562         1         0   
4    0.226957  0.229270  0.436957   0.186900  1600         1         0   
..        ...       ...       ...        ...   ...       ...       ...   
726  0.254167  0.226642  0.652917   0.350133  2114         1         0   
727  0.253333  0.255046  0.590000   0.155471  3095         1         0   
728  0.253333  0.242400  0.752917   0.124383  1341         1         0   
729  0.255833  0.231700  0.483333   0.350754  1796         1         0   
730  0.215833  0.223487  0.577500   0.154846  2729         1         0   

     season_3  season_4  weathersit_1  weathersit_2  weathersit_3  \
0           0         0             0             1             0   
1           0         0             0             1             0   
2           0         0             1             0             0   
3           0         0             1             0             0   
4           0         0             1             0             0   
..        ...       ...           ...           ...           ...   
726         0         0             0             1             0   
727         0         0             0             1             0   
728         0         0             0             1             0   
729         0         0             1             0             0   
730         0         0             0             1             0   

     workingday_0  workingday_1  
0               1             0  
1               1             0  
2               0             1  
3               0             1  
4               0             1  
..            ...           ...  
726             0             1  
727             0             1  
728             1             0  
729             1             0  
730             0             1  

[731 rows x 14 columns]